arrowParens: "always"
bracketSpacing: true
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 80
proseWrap: "always"
quoteProps: "as-needed"
semi: true
singleQuote: true
tabWidth: 2
trailingComma: "es5"
useTabs: false
# {
#   'trailingComma': 'all',
#   'singleQuote': true,
#   'printWidth': 100,
#   'arrowParens': 'avoid',
#   'endOfLine': 'auto',
# }
